project:
  name: visign
  environment: dev
service:
  name: visign-ai
  component: ai
  type: fastapi
  port: 8000
  containerPort: 8000
image:
  repository: visigndevacrbhx5po.azurecr.io/visign-ai
  tag: dev-badd1b0
  pullPolicy: IfNotPresent
replicaCount: 1
probes:
  enabled: true
  path: /health
ingress:
  enabled: false
keyVault:
  enabled: false
migration:
  enabled: false
topologySpread:
  enabled: false
