project:
  name: visign
  environment: dev
service:
  name: visign-web
  component: web
  type: nextjs
  port: 3000
  containerPort: 3000
image:
  repository: visigndevacrbhx5po.azurecr.io/visign-web
  tag: dev-59d7946
  pullPolicy: IfNotPresent
replicaCount: 1
env:
  - name: NODE_ENV
    value: production
  - name: NEXT_PUBLIC_API_URL
    value: /api/predict
probes:
  enabled: true
  path: /
ingress:
  enabled: true
  className: nginx
  host: dev.visign-uit.id.vn
  tlsSecretName: visign-tls-dev
  clusterIssuer: letsencrypt-http
  paths:
    - path: /api/predict
      pathType: Prefix
      serviceName: visign-ai
      servicePort: 8000
    - path: /api/predict-keypoints
      pathType: Prefix
      serviceName: visign-ai
      servicePort: 8000
    - path: /api/videos
      pathType: Prefix
      serviceName: visign-ai
      servicePort: 8000
    - path: /api/topics
      pathType: Prefix
      serviceName: visign-ai
      servicePort: 8000
    - path: /api/labels
      pathType: Prefix
      serviceName: visign-ai
      servicePort: 8000
    - path: /
      pathType: Prefix
      serviceName: visign-web
      servicePort: 3000
keyVault:
  enabled: true
  providerClassName: visign-kv-secrets
  keyVaultName: visign-dev-kv-bhx5po
  tenantId: "c7aee1e3-c9fb-4247-865d-ca9c9dde9ad3"
  userAssignedIdentityID: "52445c31-7eb9-41b8-b7c8-b35fab2343fc"
  objects:
    - objectName: DATABASE-URL
      objectType: secret
    - objectName: CLERK-SECRET-KEY
      objectType: secret
    - objectName: CLERK-PUBLISHABLE-KEY
      objectType: secret
  secretObjects:
    - objectName: DATABASE-URL
      key: DATABASE_URL
    - objectName: CLERK-SECRET-KEY
      key: CLERK_SECRET_KEY
    - objectName: CLERK-PUBLISHABLE-KEY
      key: NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY
migration:
  enabled: true
  image:
    repository: visigndevacrbhx5po.azurecr.io/visign-web-migrator
    tag: dev-59d7946
  command: ["npm"]
  args: ["run", "db:bootstrap"]
topologySpread:
  enabled: false
