grafana:
  enabled: true
  service:
    type: ClusterIP

  sidecar:
    dashboards:
      enabled: true
      label: grafana_dashboard
      searchNamespace: ALL
    datasources:
      enabled: true

prometheus:
  prometheusSpec:
    retention: 7d
    scrapeInterval: 30s

    serviceMonitorSelectorNilUsesHelmValues: false
    serviceMonitorNamespaceSelector: {}

    podMonitorSelectorNilUsesHelmValues: false
    podMonitorNamespaceSelector: {}

    ruleSelectorNilUsesHelmValues: false
    ruleNamespaceSelector: {}

alertmanager:
  enabled: true