apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: appset-platform-addons
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - name: cluster-addons
            namespace: cert-manager
            chartPath: platform/charts/cluster-addons

  template:
    metadata:
      name: "{{name}}"
    spec:
      project: platform

      source:
        repoURL: https://github.com/visign-uit/visign-gitops
        targetRevision: main
        path: "{{chartPath}}"
        helm:
          releaseName: "{{name}}"

      destination:
        server: https://kubernetes.default.svc
        namespace: "{{namespace}}"

      syncPolicy:
        syncOptions:
          - CreateNamespace=true
        automated:
          prune: true
          selfHeal: true
