apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: appset-services-prod
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - project: visign
            service: web
            env: prod
            clusterName: aks-visign-prod
            namespace: visign
            chartPath: platform/charts/app-service
            valuesPath: projects/visign/environments/prod/web.values.yaml

          - project: visign
            service: ai
            env: prod
            clusterName: aks-visign-prod
            namespace: visign
            chartPath: platform/charts/app-service
            valuesPath: projects/visign/environments/prod/ai.values.yaml

  template:
    metadata:
      name: "{{project}}-{{service}}-{{env}}"
      labels:
        project: "{{project}}"
        service: "{{service}}"
        env: "{{env}}"

    spec:
      project: "{{project}}"

      sources:
        - repoURL: https://github.com/visign-uit/visign-gitops
          targetRevision: main
          path: "{{chartPath}}"
          helm:
            valueFiles:
              - "$values/{{valuesPath}}"

        - repoURL: https://github.com/visign-uit/visign-gitops
          targetRevision: main
          ref: values

      destination:
        name: "{{clusterName}}"
        namespace: "{{namespace}}"

      syncPolicy:
        syncOptions:
          - CreateNamespace=true
