apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: appset-monitoring-prod
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - name: monitoring-prod
            env: prod
            clusterName: aks-visign-prod
            namespace: monitoring

  template:
    metadata:
      name: "{{name}}"
      labels:
        env: "{{env}}"

    spec:
      project: platform

      sources:
        - repoURL: https://prometheus-community.github.io/helm-charts
          chart: kube-prometheus-stack
          targetRevision: 77.0.0
          helm:
            releaseName: monitoring
            valueFiles:
              - $values/platform/helm-values/monitoring/prod.values.yaml

        - repoURL: https://github.com/visign-uit/visign-gitops
          targetRevision: main
          ref: values

      destination:
        name: "{{clusterName}}"
        namespace: "{{namespace}}"

      syncPolicy:
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true