apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: visign
  namespace: argocd
spec:
  description: Visign application project

  sourceRepos:
    - https://github.com/visign-uit/visign-gitops

  destinations:
    - name: aks-visign-dev
      namespace: visign
    - name: aks-visign-prod
      namespace: visign

  clusterResourceWhitelist:
    - group: ""
      kind: Namespace

  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
