apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: platform
  namespace: argocd
spec:
  description: Platform-level addons

  sourceRepos:
    - https://github.com/visign-uit/visign-gitops

  destinations:
    - name: aks-visign-dev
      namespace: cert-manager
    - name: aks-visign-prod
      namespace: cert-manager
    - name: aks-visign-dev
      namespace: kube-system
    - name: aks-visign-prod
      namespace: kube-system
    - name: aks-visign-dev
      namespace: ingress-nginx
    - name: aks-visign-prod
      namespace: ingress-nginx
    - name: aks-visign-dev
      namespace: monitoring
    - name: aks-visign-prod
      namespace: monitoring

  clusterResourceWhitelist:
    - group: "*"
      kind: "*"

  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
