project:
  name: visign
  owner: uit
  description: Visign web and AI platform
  sourceRepo: https://github.com/visign-uit/ci-workflow-of-visign
  gitopsRepo: https://github.com/visign-uit/visign-gitops
domains:
  base: visign-uit.id.vn
  dev: dev.visign-uit.id.vn
  prod: prod.visign-uit.id.vn
