{{- if .Values.keyVault.enabled }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Values.keyVault.providerClassName }}
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/sync-wave: "-2"
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: {{ .Values.keyVault.userAssignedIdentityID | quote }}
    keyvaultName: {{ .Values.keyVault.keyVaultName | quote }}
    tenantId: {{ .Values.keyVault.tenantId | quote }}
    objects: |
      array:
        {{- range .Values.keyVault.objects }}
        - |
          objectName: {{ .objectName }}
          objectType: {{ .objectType }}
        {{- end }}

  {{- if .Values.keyVault.secretObjects }}
  secretObjects:
    - secretName: {{ .Values.service.name }}-secrets
      type: Opaque
      data:
        {{- range .Values.keyVault.secretObjects }}
        - objectName: {{ .objectName }}
          key: {{ .key }}
        {{- end }}
  {{- end }}
{{- end }}