apiVersion: v1
kind: Service
metadata:
  name: { { .Values.service.name } }
  labels:
    app.kubernetes.io/name: { { .Values.service.name } }
    app.kubernetes.io/part-of: { { .Values.project.name } }
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: { { .Values.service.name } }
  ports:
    - name: http
      port: { { .Values.service.port } }
      targetPort: http
