name: Validate Bicep

on:
  pull_request:
    branches: [main]
    paths:
      - "infra/bicep/**"

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Azure CLI
        uses: azure/CLI@v2
        with:
          inlineScript: |
            az version

      - name: Build Bicep
        run: |
          az bicep build --file infra/bicep/main.bicep
